spring:
  config.import: vault://
  cloud:
    vault:
      reactive:
        enabled: false
      enabled: true
      uri: https://vault.adeo.no
      authentication: KUBERNETES
      kubernetes:
        role: fpsoknad-oppslag
        kubernetes-path: kubernetes/prod/fss
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kv:
        enabled: true
        backend: kv/prod/fss
        application-name: fpsoknad-oppslag/teamforeldrepenger
        default-context: fpsoknad-oppslag/teamforeldrepenger
