name: Build PR or branch

on:
  pull_request:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sett opp Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Kompiler
        run: |
          mvn install --settings .github/.m2/settings.xml

      - name: Sonar analyse
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn jacoco:prepare-agent jacoco:report sonar:sonar --settings .github/.m2/settings.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
