name: Deployment pipeline q1

on:
    push:
        branches:
            - master
env:
    IMAGE_BASE: ghcr.io/${{ github.repository }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sett opp Java  15
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt'
          cache: 'maven'

      - name: Hent tag
        run: |
          echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Kompiler
        run: |
          mvn versions:set -DnewVersion=${TAG}
          mvn clean install --batch-mode --quiet --settings .github/.m2/settings.xml

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg, tag og push Docker image
        run: |
          docker build --pull --tag ${IMAGE_BASE}:${TAG} --tag ${IMAGE_BASE}:latest .
          docker push ${IMAGE_BASE} --all-tags

      - name: Lukk gamle bygg-issues
        uses: actions/github-script@v5.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['bygg']
            }).then(response => {
              response.data.forEach(issue => {
                github.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              });
            });

      - name: Opprett issue, trigg deploy til dev-fss
        if: success()
        uses: actions/github-script@v5.1.0
        with:
          github-token: ${{secrets.NOTIFICATION}}
          script: |
              github.issues.create( {
                owner: context.issue.owner,
                repo: context.issue.repo,
                labels: ['bygg'],
                title: 'Deploy av ${{ env.TAG }}',
                body: '${{ github.sha }}'})
              .then(response => {
                      const issue = { owner: context.issue.owner,
                      repo: context.issue.repo,
                      issue_number: response.data.number }
                     github.issues.createComment({...issue,
                            title: 'Deploy av ${{ env.TAG }}',
                            body: '/promote dev-fss'})
               });
