name: Build PR or branch

on:
  pull_request:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sett opp Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Kompiler
        run: |
          mvn package --settings .github/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
